# Generated by Django 2.2.12 on 2020-04-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.IntegerField(choices=[('food_grocery', 'Food / Grocery'), ('medicine', 'Medicines'), ('feeling_sick', 'Feeling Sick')])),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('pin_code', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('declined', 'Declined')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_people', models.IntegerField()),
                ('food_grocery_type', models.CharField(blank=True, choices=[('food', 'Food'), ('grocery', 'Grocery')], max_length=250, null=True)),
                ('food_grocery_type_detail', models.CharField(blank=True, max_length=250, null=True)),
                ('medicine_request_detail', models.CharField(blank=True, max_length=250, null=True)),
                ('feeling_sick', models.BooleanField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_detail', to='registerrequest.PeopleRequest')),
            ],
        ),
    ]
