# Generated by Django 2.2.12 on 2020-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplerequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=250),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='request_type',
            field=models.CharField(choices=[('food_grocery', 'Food / Grocery'), ('medicine', 'Medicines'), ('feeling_sick', 'Feeling Sick')], max_length=250),
        ),
    ]
