# Generated by Django 2.2.12 on 2020-04-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerrequest', '0002_auto_20200405_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetail',
            name='food_grocery_type',
            field=models.CharField(blank=True, choices=[('requestFood', 'Food'), ('requestGrocery', 'Grocery'), ('requestBoth', 'Both')], max_length=250, null=True),
        ),
    ]
