# Generated by Django 2.2.12 on 2020-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerrequest', '0003_auto_20200410_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetail',
            name='feeling_sick_detail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
