# Generated by Django 2.2.12 on 2020-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerrequest', '0004_requestdetail_feeling_sick_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetail',
            name='no_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
